import { Router } from "express";
import * as c from "../controllers/community.controller.js";
import { protect } from "../middlewares/auth.middleware.js";
const r = Router();
r.route("/").get(c.list).post(protect, c.create);
r.get("/:id", c.get);
r.delete("/:id", protect, c.remove);
r.put("/:id/join", protect, c.requestJoin);
r.put("/:id/request", protect, c.requestJoin);
r.put("/:id/leave", protect, c.leave);
r.put("/:id/requests/:userId/approve", protect, c.approveRequest);
r.put("/:id/requests/:userId/reject", protect, c.rejectRequest);
export default r;
